# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editStudent.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(663, 440)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(390, 40, 231, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 40, 172, 22))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEditPrimaryName = QtGui.QLineEdit(self.widget)
        self.lineEditPrimaryName.setObjectName(_fromUtf8("lineEditPrimaryName"))
        self.horizontalLayout_6.addWidget(self.lineEditPrimaryName)
        self.widget1 = QtGui.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(20, 80, 182, 22))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEditPrimaryNumber = QtGui.QLineEdit(self.widget1)
        self.lineEditPrimaryNumber.setObjectName(_fromUtf8("lineEditPrimaryNumber"))
        self.horizontalLayout_7.addWidget(self.lineEditPrimaryNumber)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 190, 231, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.widget2 = QtGui.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(20, 30, 172, 22))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.widget2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEditSecondaryName = QtGui.QLineEdit(self.widget2)
        self.lineEditSecondaryName.setObjectName(_fromUtf8("lineEditSecondaryName"))
        self.horizontalLayout_8.addWidget(self.lineEditSecondaryName)
        self.widget3 = QtGui.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(20, 60, 182, 22))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_9 = QtGui.QLabel(self.widget3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEditSecondaryNumber = QtGui.QLineEdit(self.widget3)
        self.lineEditSecondaryNumber.setObjectName(_fromUtf8("lineEditSecondaryNumber"))
        self.horizontalLayout_9.addWidget(self.lineEditSecondaryNumber)
        self.widget4 = QtGui.QWidget(Dialog)
        self.widget4.setGeometry(QtCore.QRect(20, 40, 334, 308))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEditStudentID = QtGui.QLineEdit(self.widget4)
        self.lineEditStudentID.setObjectName(_fromUtf8("lineEditStudentID"))
        self.horizontalLayout.addWidget(self.lineEditStudentID)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditStudentName = QtGui.QLineEdit(self.widget4)
        self.lineEditStudentName.setObjectName(_fromUtf8("lineEditStudentName"))
        self.horizontalLayout_2.addWidget(self.lineEditStudentName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEditStudentLastName = QtGui.QLineEdit(self.widget4)
        self.lineEditStudentLastName.setObjectName(_fromUtf8("lineEditStudentLastName"))
        self.horizontalLayout_3.addWidget(self.lineEditStudentLastName)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dateEdit = QtGui.QDateEdit(self.widget4)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.widget4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.textEditSpecialNotes = QtGui.QTextEdit(self.widget4)
        self.textEditSpecialNotes.setObjectName(_fromUtf8("textEditSpecialNotes"))
        self.horizontalLayout_5.addWidget(self.textEditSpecialNotes)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(390, 330, 225, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.btnSave = QtGui.QPushButton(self.splitter)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.btnDelete = QtGui.QPushButton(self.splitter)
        self.btnDelete.setEnabled(False)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.btnClose = QtGui.QPushButton(self.splitter)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Primary Contact Person", None))
        self.label_6.setText(_translate("Dialog", "Name:", None))
        self.label_7.setText(_translate("Dialog", "Number:", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Secondary Contact Person", None))
        self.label_8.setText(_translate("Dialog", "Name:", None))
        self.label_9.setText(_translate("Dialog", "Number:", None))
        self.label.setText(_translate("Dialog", "Student ID:", None))
        self.label_2.setText(_translate("Dialog", "First Name:", None))
        self.label_3.setText(_translate("Dialog", "Last Name:", None))
        self.label_4.setText(_translate("Dialog", "Date of Birth:", None))
        self.label_5.setText(_translate("Dialog", "Special Notes:", None))
        self.btnSave.setText(_translate("Dialog", "Save", None))
        self.btnDelete.setText(_translate("Dialog", "Delete", None))
        self.btnClose.setText(_translate("Dialog", "Close", None))

